services:
    - type: web
      name: laravel-time-tracker
      runtime: docker
      plan: free
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_KEY
            value: base64:sUdjekfRpP1dWZ6TpX2pbX5mYVL2idYHpLTo0Gq+3vw=
          - key: APP_URL
            value: https://laravel-time-tracker.onrender.com
          - key: DB_CONNECTION
            value: sqlite
          - key: DB_DATABASE
            value: /var/www/html/database/database.sqlite
